# ===============================
# PERFIL PROD - Oracle 19C + JNDI (WebLogic)
# ===============================

# DATASOURCE - JNDI (configurado en WebLogic)
spring.datasource.jndi-name=jdbc/SICOBERTURA

# JPA / HIBERNATE
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.ddl-auto=none

# Seguridad habilitada en produccion
app.security.enabled=true
